name: Beta publish to NPM

on:
  push:
    branches: [ beta, stg*, hotfix* ]

  pull_request:
    types: [ closed ]
    branches: [ stg*, hotfix* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - uses: technote-space/get-diff-action@v2
      id: git_diff
      with:
        PREFIX_FILTER: packages/core/

    - name: Check core modified
      run: echo "Hello ${{ steps.git_diff.outputs.diff }}!"
      if: steps.git_diff.outputs.diff

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

