name: Beta publish to NPM

on:
  push:
    branches: [ beta, stg*, hotfix* ]

  pull_request:
    types: [ closed ]
    branches: [ stg*, hotfix* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - uses: technote-space/get-diff-action@v2
      id: git_diff
      with:
        PREFIX_FILTER: packages/core/

    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1
      with:
        file-name: ./packages/core/package.json

    - run: npm ci

