name: Check and publish npm packages

on:
  push:
    branches: [ beta, stg*, hotfix* ]

  pull_request:
    types: [ closed ]
    branches: [ stg*, hotfix* ]

jobs:
  check_and_publish_npm_packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Publish action
      uses: ./.github/publish-action
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
